name: Build backend+frontend for deployment

on:
  workflow_call:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm ci backend
        run: npm ci

      - name: Pull & update frontend submodule
        run: git submodule update --init

      - name: npm ci frontend
        working-directory: ./UKK-tiketit
        run: npm ci

      - name: Test and lint frontend
        working-directory: ./UKK-tiketit
        run: |
          npm run test:prod
          npm run lint

      - name: Build frontend
        working-directory: ./UKK-tiketit
        run: npm run build

      - name: Move built frontend to static folder
        run: mv ./UKK-tiketit/dist/tikettisysteemi ./static

      - name: Delete unnecessary stuff
        run: rm -rf UKK-tiketit

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip
