name: Build backend+frontend for deployment

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install backend
        run: npm ci

      - name: Pull & update frontend submodule
        run: git submodule update --init

      - name: npm install, build, test and lint frontend
        run: |
          npm run build:ui
          npm run test:ui
          npm run lint:ui

      - name: delete unnecessary stuff
        run: rm -rf UKK-tiketit

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip