name: Run backend tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm ci
        run: npm ci

      - name: npm run test
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGDATABASE: database
          PGUSER: user
          PGPASSWORD: password
        run: npm run test
